### ISSUE TITLE
REKitを導入した状態でMPMoviePlayerViewControllerのインスタンスを作成すると例外が出る

### ISSUE THREAD

**Issue by mitsuyoshi-yamazaki** [zuccoi/REKit#7]
REKit1.0.1を導入した状態でMPMoviePlayerViewControllerのインスタンスを作成すると以下の例外が出る

**\* Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <AVPlayerLayer 0x8693270> for the key path "contentsAreFlipped" from <AVPlayerLayer 0x8693270> because it is not registered as an observer.'

スタックはこんな感じ
#11 0x000050fd in -[NSObject(REObserver) REObserver_X_removeObserver:forKeyPath:context:] at /REKit/REKit/NSObject+REObserver.m:338
#12 0x00006934 in -[NSObject(REObserver) stopObserving] at /REKit/REKit/NSObject+REObserver.m:553
#13 0x00005cc2 in -[NSObject(REObserver) REObserver_X_dealloc] at /REKit/REKit/NSObject+REObserver.m:402
#14 0x000072fa in -[NSObject(REResponder) REResponder_X_dealloc] at /REKit/REKit/NSObject+REResponder.m:147

**Comment by zuccoi** [comment]
報告ありがとうございます、調査／修正します。
